version: 2

builds:
  - main: .
    binary: snipfly
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: txperl
      name: homebrew-tap
      token: "{{ .Env.TAP_REPO_TOKEN }}"
    name: snipfly
    homepage: https://github.com/txperl/snipfly
    description: A TUI tool for running multiple code snippets, in a single terminal tab.
    license: MIT
    install: |
      bin.install "snipfly"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
