version: 2

builds:
  - main: .
    binary: snipfly
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: txperl
      name: homebrew-tap
      token: "{{ .Env.TAP_REPO_TOKEN }}"
    name: snipfly
    binaries:
      - snipfly
    homepage: https://github.com/txperl/snipfly
    description: A TUI tool for running multiple code snippets, in a single terminal tab.
    license: MIT

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
